
# Set 256 color support
set -g default-terminal "xterm-256color"
# set -g status-utf8 on
# set -g utf8 on

# Set the base index for windows to 1 instead of 0
set -g base-index 1
# Set the base index for panes to 1 instead of 0
set -g pane-base-index 1

# set to ctrl - space
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Set bind key to reload configuration file
bind r source-file ~/.tmux.conf \; display "Reloaded!"

setw -g monitor-activity on
set -g visual-activity on

# splitting panes with | and -
bind | split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
# Enable mouse support
set -g mouse on

# Set vi as the default editor
set -g status-keys vi

# Set mode of vim
setw -g mode-keys vi


# ---------------- #
# Define Colors    #
# ---------------- #
GRAY="#808080"
BLUE="#569CD6"
DARK_BLUE="#223E55"
RED="#EE4646"
YELLOW="#CCCC99"
BACKGROUND="#000000"
FOREGROUND="#CCCCCC"

# ----------------- #
# Define Status Bar #
# ----------------- #
set -g status-interval 1
set -g status-style bg=$BACKGROUND,fg=$BLUE

# ------------ #
# Define Panes #
# ------------ #
set -g pane-border-style fg=$DARK_BLUE
set -g pane-active-border-style fg=$BLUE

# ---------------- #
# Define Left Side #
# ---------------- #
set -g status-left ""

# -------------- #
# Define Windows #
# -------------- #
set -g window-status-style bg=$BACKGROUND,fg=$GRAY
set -g window-status-format "#[]#I:#W #F" 
set -g window-status-current-format "#[fg=$BLUE  underscore]#W"
# set -g window-status-activity-style "#[fg=$BLUE bold]#W"
set -g window-status-bell-style fg=$YELLOW
set -g window-status-separator " | "

set -g window-style default

# ----------------- #
# Define Right Side #
# ----------------- #
set -g status-right-length 150
set -g status-right "#(~/bin/battery Discharging; ~/bin/battery Charging)el | %e %B %R"

# source "/usr/lib/python3.9/site-packages/powerline/bindings/tmux/powerline.conf"

# set tmux escape-time
set-option -sg escape-time 10

#set focus-events for nvim autoread
set-option -g focus-events on

#set 256 color options for terminal
set-option -g default-terminal "screen-256color"

#set Tc/RGB capability for 'termguicolors'
set-option -sa terminal-overrides ',XXX:RGB'
